### ISSUE TITLE
topic stats

### ISSUE THREAD

**Issue by behrad** [davedoesdev/qlobber#12]
Is there any chance qlobber implements performant methods for:

1. all subscribed topics count?
2. subscriptions count matching a topic (currently `.match().length` does this)

This will simplify aedes counting offline subscriptions inside cached-persistence

**Comment by davedoesdev** [comment]
Having count has occurred to me before. I'll have a think. Thanks for
opening the issue.

**Comment by davedoesdev** [comment]
Subscriptions count matching a topic can be done easily without changing qlobber core. See the test/example here: https://github.com/davedoesdev/qlobber/blob/master/test/match_count.js
Since each Qlobber type stores things differently, it's impossible to do this generically.

**Comment by davedoesdev** [comment]
Closing because I've shown it's easy to add the required functionality by subclassing `Qlobber` (or `QlobberDedup`, as required) and overriding methods.
