### ISSUE TITLE
remove duplicates

### ISSUE THREAD

**Issue by roccomuso** [davedoesdev/qlobber#13]
best way to handle/remove duplicates in the trie?

**Comment by davedoesdev** [comment]
@roccomuso have you tried [`QlobberDedup`](https://github.com/davedoesdev/qlobber#qlobberdedupoptions)?

**Comment by roccomuso** [comment]
@davedoesdev no I have not. The initial description wasn't totally clear to me.

**Comment by davedoesdev** [comment]
Please let me know if it works for you. I've added a sentence to the `match` docs to point to `QlobberDedup`. Thanks for the feedback!

**Comment by roccomuso** [comment]
@davedoesdev thanks, a lot better.

**Comment by davedoesdev** [comment]
@roccomuso no problem
