### ISSUE TITLE
Remove the of statements

### ISSUE THREAD

**Issue by roccomuso** [davedoesdev/qlobber#15]
We might consider the idea to switch from a `for (w of st.keys())` statement to a more common one `Object.keys(st.keys())`... right now webpack's uglify doesn't support the `of` keyword.

If we change this loop syntax with an older one, anyone can build and use the module also on the browser.

**Comment by davedoesdev** [comment]
In 2018 I'd like to write ES6 :)

https://github.com/webpack-contrib/uglifyjs-webpack-plugin says:

> webpack =< v3.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0

It looks like you can work around it in `webpack.config.js`, until webpack 4.0.0 arrives.

**Comment by davedoesdev** [comment]
I think maybe the `webpack.config.js` is fine: https://github.com/facebook/create-react-app/blob/25184c4e91ebabd16fe1cde3d8630830e4a36a01/packages/react-scripts/config/webpack.config.prod.js#L385

But I can't see where it depends on `uglifyjs-webpack-plugin`.

**Comment by davedoesdev** [comment]
Ah, here: https://github.com/facebook/create-react-app/blob/3767d91886823349ec46288d9b7ea48d4149890a/packages/react-scripts/package.json#L60

which is version 1.1.6 so should be fine

**Comment by davedoesdev** [comment]
Looks like the fix came in here 15 days ago: https://github.com/facebook/create-react-app/commit/ff544949b904cf4d2ea5fe926fd25ff367a59999

**Comment by davedoesdev** [comment]
https://github.com/facebook/create-react-app/pull/3618

**Comment by davedoesdev** [comment]
@roccomuso did the latest `create-react-app` work?

**Comment by roccomuso** [comment]
@davedoesdev yes, thanks :)
