### ISSUE TITLE
SharedArrayBuffer implementation

### ISSUE THREAD

**Issue by behrad** [davedoesdev/qlobber#16]
Is there any chance we have an implementation over a SharedArrayBuffer @davedoesdev ?
This could help to use qlobber trie within a multi threaded nodejs process

**Comment by davedoesdev** [comment]
Good idea. Shall we consider the API?

**Comment by davedoesdev** [comment]
Are you thinking same API but backed by SharedArrayBuffer?

**Comment by behrad** [comment]
> Are you thinking same API but backed by SharedArrayBuffer?

Exactly.
Something like `new Qlobber(new SharedArrayBuffer( 12Gigs of buffer ))`
I don't know how to create a native Set/Map view over that buffer array however

**Comment by davedoesdev** [comment]
OK, I'll have a think.
What about concurrent mutation of the Qlobber, is that required?

**Comment by behrad** [comment]
> What about concurrent mutation of the Qlobber, is that required?

No. let's do it simple.

**Comment by davedoesdev** [comment]
Another option is to write a C++ addon

**Comment by behrad** [comment]
> Another option is to write a C++ addon

as a C++ trie?

**Comment by davedoesdev** [comment]
> > Another option is to write a C++ addon
> 
> as a C++ trie?

Yes, or at least the storage behing the Qlobber.

**Comment by behrad** [comment]
Sounds good, and what if it could be also wrap-able by a Redis module :)

**Comment by davedoesdev** [comment]
I'm not too familiar with Redis. How does the module system work?

**Comment by behrad** [comment]
https://redis.io/topics/modules-intro
https://redis.io/topics/modules-native-types
https://dzone.com/articles/writing-redis-modules
https://github.com/cmsc22000-project-2018/redis-tries

**Comment by davedoesdev** [comment]
I'm not sure the C++ addon will work with JS objects

> JavaScript objects are only valid in one context, and will likely cause a crash when accessed from the wrong context or from a different thread than the one on which they were created.

So we'd have to have a typed trie, which in turn means marshalling to/from native types and drop in performance.

It might be better to use SharedMemoryBuffer but limit the type of data that can be stored, to fixed size chunks of memory.

**Comment by behrad** [comment]
> It might be better to use SharedMemoryBuffer but limit the type of data that can be stored, to fixed size chunks of memory.

I am on it, as long as it is compatible with QlobberDedup API

**Comment by davedoesdev** [comment]
First thing I think is to see what type of JS object access is allowed from multiple C++ threads

**Comment by davedoesdev** [comment]
I'll take a look, might be a few days though

**Comment by behrad** [comment]
> First thing I think is to see what type of JS object access is allowed from multiple C++ threads

https://nodejs.org/api/worker_threads.html
https://stackoverflow.com/questions/51053222/nodejs-worker-threads-shared-object-store



> I'll take a look, might be a few days though

👍

**Comment by davedoesdev** [comment]
The problem is the _values_. They can't be accessed from multiple threads when returned from a match.

Is your Qlobber too large to copy between threads once constructed?

**Comment by davedoesdev** [comment]
A left-field option:

- Fix https://github.com/codemix/malloc/issues/2
- Use https://github.com/codemix/reign

**Comment by behrad** [comment]
> Is your Qlobber too large to copy between threads once constructed?

it is around 15G so I can't use pm2/cluster to balance my heavy load.
- One way is sharing that 15G around multiple threads
- The other would be sharding (using may be [Upring](https://github.com/upringjs/upring))

**Comment by davedoesdev** [comment]
@behrad ah I see. What types are you storing as values?

**Comment by behrad** [comment]
> What types are you storing as values?

Aedes uses QlobberDedup and values are subscription objects
```
{
clientId: 'gu23/dssdfd23/skh23kjh',
topic: 't1111/r222222/c333333/g444444/h555555'
qos: 1
}
```

**Comment by davedoesdev** [comment]
I wonder what the cost of decoding those objects from C++ (or a SharedArrayBuffer view) to JS would be (using JSON for example). Probably quite a lot.

**Comment by behrad** [comment]
Should see how much it helps for scalability!

**Comment by davedoesdev** [comment]
@behrad yes that's true.

I thought Aedes uses a custom Qlobber:

https://github.com/davedoesdev/qlobber/blob/master/aedes/qlobber-sub.js

?

**Comment by davedoesdev** [comment]
Yes, it still does: https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L4

**Comment by behrad** [comment]
> I thought Aedes uses a custom Qlobber:

exactly

**Comment by behrad** [comment]
Updated my mistake https://github.com/davedoesdev/qlobber/issues/16#issuecomment-544814006

**Comment by davedoesdev** [comment]
I think I might first try https://github.com/codemix/reign with standard Buffer and see what performance is like.

I've written a few modules with C++ addons and it's nice to avoid them if possible :)
It should be possible to make that work too though, with cost of decoding into JS due to restriction on accessing JS objects from different thread contexts. Also it'll require passing the location of the memory between threads somehow (doable I think).

**Comment by davedoesdev** [comment]
`wip-native` branch has QlobberSub.native which is a C++ addon implementation. This has no async/thread support yet. But the core is all STL which should mean no JS thread sharing problems.

Next step is to implement async (using libuv's thread pool), then access from separate worker threads.

**Comment by davedoesdev** [comment]
Native implementations now pass all tests. Next step is async methods, then worker thread support.

**Comment by davedoesdev** [comment]
OK async methods for native implementation now implemented and pass tests. This is still on `wip-native` branch. You can run multiple async operations on the same matcher and they'll get run in the libuv thread pool (up to the normal libuv thread pool limit).

The trie is protected by a readers-writer lock.

Next step is worker threads.

**Comment by davedoesdev** [comment]
OK `wip-native` branch now has worker thread support. No docs yet but tests in https://github.com/davedoesdev/qlobber/blob/wip-native/test/dedup_threads.js

State is passed by native address so crashes can occur if the state isn't referenced by at least one matcher (or `add_ref` is called to keep it around).

**Comment by davedoesdev** [comment]
Published as v4.0.0 and README updated.

There is also a `QlobberSub.native` which supports worker threads (and async), which aedes could use.

**Comment by davedoesdev** [comment]
@behrad is intended for aedes/mosca?

**Comment by behrad** [comment]
Yup but have no time to check it yet. Eager to see test results yet
