### ISSUE TITLE
Split native code in its own module

### ISSUE THREAD

**Issue by mcollina** [davedoesdev/qlobber#17]
Pure JS modules are extremely useful, they are tiny and they can be installed without much effort. 
Requiring a native addon adds a significant barrier to use this module where we should not worry about, from serverlesss to corporate environments to Electron, requiring a binary module makes it __harder__ to use. In Aedes, fastify-gql and many other cases, we don't need this.

Given that the use of a native addon is optional already, would you be interested in moving the binary part in a separate module that is not installed by default (so no optionalDependency or peerDependency from this module)? Then whoever needs the worker and async functionality will be able to use the new package.

Another alternative is a qlobber-async package that use qlobber and add the async/worker_thread functionality.

**Comment by davedoesdev** [comment]
Hi @mcollina good to hear from you!
I'm happy to entertain changes but I'm not quite clear on the problem. If the native addon compile fails then the module is still installed, it's just that the async functionality isn't available.
Can you clarify why that's a problem?

**Comment by davedoesdev** [comment]
I've been thinking about this and I'll split out the native part into a separate module.

The native module won't be usable on its own, it'll have to be passed into qlobber to get the async features.

**Comment by mcollina** [comment]
Thanks for understanding @davedoesdev!

**Comment by davedoesdev** [comment]
Fixed in v5.0.0. Please let me know if it works for you.

**Comment by mcollina** [comment]
Awesome, thanks!
