### ISSUE TITLE
[Feature Request] Advanced matching

### ISSUE THREAD

**Issue by sirzento** [davedoesdev/qlobber#26]
I would love if there would be a more advanced way of matching. For example, If someone uses a number system, one would like to only match if a number is smaller/bigger than X. 
That would look like that: `matcher.add("test.123.15.[<5].*", "")` to match everything that is smaller that 5.

Or even "Or logic" like `matcher.add("test.123.15.[4|5|6].*")` to only match if the last number is 4, 5 or 6.

Is something like that possible and easy to make?

**Comment by davedoesdev** [comment]
Hi @sirzento your idea is possible, however there are dependents of qlobber that need it to be fast and I think adding in extra matcher logic would introduce too much overhead. I think unfortunately this is something that would have to live in a fork.
