### ISSUE TITLE
matching a topic with * in it

### ISSUE THREAD

**Issue by vinassefranche** [davedoesdev/qlobber#7]
Hi, 

i'm wondering if there's a possibility with your module to use a star in the topics to check (not in the topic given for check)

For example, let's say i have a message with topic : foo.*.bar. I would like these topics to match with it : 
foo.foobar.bar, foo.*.bar, *.foo.bar.
That is to say, any word can be in second place, it will be a match.

Is there a possibility to achieve this with your module?

Thanks in advance for you answer!

Regards

**Comment by davedoesdev** [comment]
Just so I can understand - you mean a single-level wildcard?

**Comment by vinassefranche** [comment]
Yes. As far as i've seen, the multiple level already works. 

Date: Fri, 8 Jan 2016 14:07:07 -0800

**Comment by davedoesdev** [comment]
Single level works AFAICT:

```javascript
> var Qlobber = require('.').Qlobber
undefined
> var matcher = new Qlobber()
undefined
> matcher.add('foo.*.bar', 'it matched')
Qlobber {
  _separator: '.',
  _wildcard_one: '*',
  _wildcard_some: '#',
  _trie: { foo: { '*': [Object] } } }
> matcher.match('foo.bar')
[]
> matcher.match('foo.one.bar')
[ 'it matched' ]
> matcher.match('foo.one.two.bar')
[]
```

**Comment by vinassefranche** [comment]
Hi, 

Thanks for your answer.

I agree that what you are writing is working. However, what seems not to be working and what i'm interessed in is the other way around. This example does not report a match while i'd like it to : 

> var Qlobber = require('.').Qlobber
> var matcher = new Qlobber()
> matcher.add('foo.one.bar', 'it matched')
> matcher.match('foo.*.bar')
[ ]

Basically, i'd like the single-level wildcard to match anything but when put in a argument of matcher.match(), not of matcher.add()

I don't know if i'm very clear so if you don't understand my problem, don't bother too much, i'll find a way by myself.

Thanks again for your answers.

**Comment by davedoesdev** [comment]
I think I get it - you want a `*` in the message's topic to skip a match level?
I'll have a think.

**Comment by davedoesdev** [comment]
What if you created a new `Qlobber` for each message and used it's topic as the pattern?
You'd have to do some performance analysis.

The problem with adding more conditional into the core logic is there are projects using qlobber which are sensitive to performance.

**Comment by vinassefranche** [comment]
I don't think you first workaround could work for me but i'll have a look.

I understand the performance issue of my demand. I just wanted to be sure i had not missed anything in your dev. I think i'll manage to modify what i need to solve my problem on my own.

Thanks anyway for all you answers!
