### ISSUE TITLE
Equality function for QlobberDedup

### ISSUE THREAD

**Issue by behrad** [davedoesdev/qlobber#9]
I don't think QlobberDedup will work with objects @davedoesdev and we are currently adding objects not strings for each topic in [aedes](https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L39-L42)

Can equality be provided with a function in Qlobber options? or ... ?

**Comment by davedoesdev** [comment]
Hi @behrad 
Do you mean the topics themselves are objects?

**Comment by behrad** [comment]
Seems es6 Sets has no comparator! 
I want to change aedes's Qlobber to QlobberDedup, since `.match + .add` combination is still slower than `dedup.add`.
We can add a string representation instead of {clientId, topic, qos} object. what dya think @mcollina ?

**Comment by behrad** [comment]
> Do you mean the topics themselves are objects?

Hey dude :)

They aren't. clientId's are. `.add(topicName, obj)` where `obj= {clientId, topicName, qos}`

**Comment by mcollina** [comment]
I'm a bit lost. Qlobber supports adding arbitrary objects as values.

**Comment by davedoesdev** [comment]
I think this is a general JS problem: lack of value types.

**Comment by behrad** [comment]
> I'm a bit lost. Qlobber supports adding arbitrary objects as values.

check [this line](https://github.com/mcollina/aedes-cached-persistence/blob/master/index.js#L40) matteo,

Currently
```js
QlobberDedup.add('topic1', 'clientId1')
QlobberDedup.add('topic1', 'clientId1')
```
works but this won't:
```js
QlobberDedup.add('topic1', {'clientId1', ...})
QlobberDedup.add('topic1', {'clientId1', ...})
```

**Comment by behrad** [comment]
> I think this is a general JS problem: lack of value types.

however I'm not sure this works `QlobberDedup.add('topic1', 'clientId1;topic1;qos')` 
since deduption should be on clientId, topic pair! ain't it?

**Comment by davedoesdev** [comment]
I'd have to use a custom set implementation - performance would no doubt be much worse that built-in `Set`.

Do you really need qlobber here? Do you need wildcards and separators? If not, you could just use a hashtable (`Map`) indexed by `clientId,topic` pair.

**Comment by davedoesdev** [comment]
Or: could you append `clientId` to the topic and store `qos`?

**Comment by mcollina** [comment]
@behrad I do not think QLobber is the right data structure to do what you plan to do there.

**Comment by behrad** [comment]
> @behrad I do not think QLobber is the right data structure to do what you plan to do there

aedes-cached-persistence is already adding objects to Qlobber, I only wanted to switch it to QlobberDedup to replace `.match .add` combo by a `.add` to be faster on subs.

I was trying even to replace objects with simple clientId's inside current implementation (named decoded Sub objects), but found out that some api methods are using that object.
- I think I should insist replacing objects inside Qlobber with simple clientId strings
- Reimplement api methods may be using an another es6 Map as @davedoesdev said.
- switch Qlobber with QlobberDedup
- this way each aedes instance will also contain a full Map of subscriptions (clientId, topics)

**Comment by mcollina** [comment]
@behrad I'm 👍  with that.

**Comment by davedoesdev** [comment]
Can you wait a couple of days. Having thought about it a bit I think it
might be possible to do something quite easily. I'll post a proposal to
this ticket later today or tomorrow when I get time.

**Comment by behrad** [comment]
sure 👍 @davedoesdev

**Comment by davedoesdev** [comment]
@behrad is this up the right street? https://github.com/davedoesdev/qlobber/blob/custom-qlobber-example/test/custom.js

May not be quite the same as your example yet. You said you needed to index by clientId _and_ topic but I wasn't sure why. If you do then I can change it for sure.

**Comment by behrad** [comment]
> is this up the right street?

Yes, that serves good. How will that perform? seems that's based on Qlobber not QlobberDedup.

> You said you needed to index by clientId and topic but I wasn't sure why

that should've been my mistake. the topic is the same as Qlobber's topic. Don't need to bring them also into value object.

**Comment by behrad** [comment]
However we should decide it [here](https://github.com/mcollina/aedes/issues/123) @davedoesdev

**Comment by davedoesdev** [comment]
Closing this as:

1. https://github.com/davedoesdev/qlobber/blob/custom-qlobber-example/test/custom.js shows that one can easily write a custom Qlobber which can be used for custom equality, without changes to Qlobber core.

2. Performance is slower than the Qlobber core implementation which uses Sets. This is open as issue #10.
